services:
  app:
    image: valentin-cuisine:latest
    container_name: valentin_cuisine_app
    ports:
      - "127.0.0.1:3026:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      UPLOAD_PATH: /app/uploads
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db
    networks:
      - valentin_network

  db:
    image: postgres:14
    container_name: valentin_cuisine_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - valentin_network

networks:
  valentin_network:

volumes:
  db_data:
  uploads_data:
